////// THIS FILE WAS CREATED BY ROSETTA FFIGEN 
////// THERE IS ABSOLUTELY NO WARRANTY THAT THOSE NAMES WILL BE THE SAME IN THE NEWER VERSIONS OF THE LIBRARY 
////// 
////// PLEASE DO NOT USE FUNCTIONS FROM THIS MODULE DIRECTLY; THOSE ARE ONLY FOR REFERENCE ONLY 
////// 

import gleam/dynamic.{type Dynamic}
