/// cancel_timer/1
/// cancel_timer/2
/// convert_time_unit/3
/// date/0
/// localtime/0
/// localtime_to_universaltime/1
/// localtime_to_universaltime/2
/// monotonic_time/0
/// monotonic_time/1
/// read_timer/1
/// read_timer/2
/// send_after/3
/// send_after/4
/// start_timer/3
/// start_timer/4
/// system_time/0
/// system_time/1
/// time/0
/// time_offset/0
/// time_offset/1
/// timestamp/0
/// universaltime/0
/// universaltime_to_localtime/1
